### PR TITLE
Submodule and few changes to help packaging

### PR DESCRIPTION
**Pull request by stefano-tronci**
Hi!
The latest changes introduced in the install script make the software hard to package for Arch Linux, as PKGBUILD mandate to have build and installation done in two separate steps, in directories that differ from the standard you provide. As such, your install script has to be bypassed.

To make things even easier, and address [this issue](https://github.com/lucianodato/speech-denoiser/issues/2), I also introduced the rnnoise dependency as a submodule. Currently, my AUR package is building from my fork as I find it more convenient.

As for installation script editing, I just did the bare minimal to make possible for an user to install from the fork by using it. I have no idea about how to use meson, but I have the feeling that it should be possible to have meson handling the build of rnnoise, and perhaps that would be the best option, so that meson/ninja can be used directly both from users and packagers with the same ease.

### CODE REVIEW

**Comment by lucianodato** [comment]
That install script shouldn't break what you had previously done for the aur package. It's just an install script for those users that doesn't know how to compile with meson. I'll have a look and let you know. As for the submodule that's great!

**Comment by lucianodato** [comment]
Ok. My bad. I removed the script for static rnnoise building. With that you shouldn't change your pkgbuild file I believe. I will re-upload it.

**Comment by CrocoDuckoDucks** [comment]
Hi! I rebased the pull request on your latest changes. I edited the scripts a little. I think the comments should be easy to read.

**Comment by lucianodato** [comment]
Thank you!

**Comment by CrocoDuckoDucks** [comment]
Nice one! You might want to edit back the README file. In my fork I had the url of the installing instructions pointing to my repo.

**Pull request merged**
